service: ses-mail-receiver

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  deploymentBucket: serverless-upload-us-east-1
  versionFunctions: false
  iamRoleStatements:
    - Effect: Allow
      Resource:
        - "arn:aws:s3:::camelon-inbox/*"
      Action:
        - s3:GetObject
        - s3:DeleteObject
    - Effect: Allow
      Resource:
        - "arn:aws:s3:::s3-mail-sender-queue/*"
      Action:
        - s3:PutObject
    - Effect: Allow
      Resource:
        Fn::Join: [":", [ "arn:aws:dynamodb", "ap-northeast-1", { Ref: AWS::AccountId }, "table/credential-store" ]]
      Action:
        - dynamodb:GetItem
        - dynamodb:Query
        - dynamodb:Scan
    - Effect: Allow
      Resource: "${s3:serverless-upload-ap-northeast-1/credstash_kms_key_arn}"
      Action:
        - kms:Decrypt

functions:
  main:
    handler: handler.main
    events:
      - s3: camelon-inbox

resources:
  Resources:
    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: { Ref: S3BucketCameloninbox }
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            Effect: Allow
            Principal:
              Service: "ses.amazonaws.com"
            Action:
              - s3:PutObject
            Resource:
              - Fn::Join: [ "", [ "arn:aws:s3:::", { Ref: S3BucketCameloninbox }, "/*" ] ]
            Condition:
              StringEquals:
                "aws:Referer": { Ref: AWS::AccountId }
